### ISSUE TITLE
history.getCurrentLocation is not a function

### ISSUE THREAD

**Issue by salex772** [ReactJSTraining/history#304]
I think docs are outdated. Package,json points to 2.1.2 whereas the latest release is 3.0.0. Anyway

    const location = history.getCurrentLocation()

does not work

**Comment by rogierschouten** [comment]
I just ran into this as well. You really need it when you start listening for changes to the location because you need the initial location.

**Comment by bhowell2** [comment]
I also was just following the README docs and checking out the api and ran into this. You can set up a listener and get the initial location though. 

E.g. `history.listen(location => do something with location object);`

As far as i can tell, this will always return the initial location? If you find/know of a case when it doesn't, let me know so I don't have some unknown errors.

**Comment by rogierschouten** [comment]
I've already worked around this in another way by now. I sure did not get an initial event until the location changed

**Comment by taion** [comment]
It's different between 2.x and 3.x. You get the initial location in 2.x with `listen`, but don't have `getCurrentLocation`; the opposite in 3.x.

**Comment by salex772** [comment]
Does npm package still point to 2.0 ?
