### ISSUE TITLE
(Facebook) BSD License text in complied code

### ISSUE THREAD

**Issue by WilliamHolmes** [ReactJSTraining/history#324]
I noticed some BSD license text in the history.js code after compilation.

history: v.2.1.2

approx: ln.157
/**
	 * Copyright 2014-2015, Facebook, Inc.
	 * All rights reserved.
	 *
	 * This source code is licensed under the BSD-style license found in the
	 * LICENSE file in the root directory of this source tree. An additional grant
	 * of patent rights can be found in the PATENTS file in the same directory.
	 */

I'm wondering which module this came from and/or if this has implications to your MIT license declaration.

**Comment by WilliamHolmes** [comment]
Think I got it.   [invariant](https://www.npmjs.com/package/invariant)

**Comment by taion** [comment]
The code in this library falls under the MIT license. The code in the packaged bundle falls under a variety of licenses, as indicated by the license text.
