### ISSUE TITLE
createLocation does not accept the state

### ISSUE THREAD

**Issue by frenzzy** [ReactJSTraining/history#325]
Documentation says ([history/blob/v3.0.0/docs/Location.md#programmatic-creation](https://github.com/ReactJSTraining/history/blob/v3.0.0/docs/Location.md#programmatic-creation)):
```js
createLocation('/a/path?a=query', { the: 'state' })
```

But source code says ([history/blob/v3.0.0/modules/LocationUtils.js#L8-L24](https://github.com/ReactJSTraining/history/blob/v3.0.0/modules/LocationUtils.js#L8-L24)):
```js
createLocation(input = '/', action = POP, key = null)
```

It was a quite convenient opportunity to create the location when you have only `href` and `state`.
Any workaround on this or plans to return functionality?

**Comment by taion** [comment]
The docs are out of date. Use a location descriptor as in the example above.

**Comment by frenzzy** [comment]
@taion can you provide a working example how to create location from `href`+`state` for latest (3.0.0) history version, please?

Can we keep this issue open until the source code and documentation are not correspond to each other?

**Comment by taion** [comment]
`createLocation({ pathname, state })`

**Comment by frenzzy** [comment]
but in your example I need to parse `href: "/path?serach#hash"` by myself to get a right `pathname`

```js
const href = '/a/path?a=query'
const state = { the: 'state' }

// previously it was
history.push(createLocation(href, state))

// now
const location = createLocation(href)
Object.assign(location.state, state)
history.push(location)

// or
history.push(createLocation({ ...createLocation(href), state }))

// or maybe it is possible to do better?
```

**Comment by taion** [comment]
That's correct. I think it'd make sense to accept a PR to add this feature, but it's not something that's really come up broadly.
